### ISSUE TITLE
Encoding issue on some reconciliation results

### ISSUE THREAD

**Issue by mphilli** [codeforkjeff/conciliator#10]
I'm using this program to perform reconciliation on a database of names, specifically attempting to retrieve LCNAF IDs (by way of VIAF). Some results, however, seem to be encountering an encoding issue of some sort. I am unsure if this has to do with OpenRefine, the conciliator program, or both. 

For example, reconciling "Menéndez Pidal, Ramón 1869-1968" results in "[MenÃ©ndez Pidal, RamÃ³n, 1869-1968.](http://id.loc.gov/authorities/names/n79021814.html)", and reconciling "Ōe, Kenzaburō 1935-" gave me [ÅŒe, KenzaburÅ�, 1935-](http://id.loc.gov/authorities/names/n81033861.html). 

Any suggestions?

**Comment by codeforkjeff** [comment]
Hi Michael,

Does your original data appear in the OpenRefine cells correctly, before you do any reconciliation? If not, that's the problem. When you create a project with your data file, there is a "Character encoding" text field that you can click, and it will bring up options to choose. If you're using UTF-8, be sure to select that. Then try reconciling again.

With the projects properly set up in this way, I'm able to reconcile your two examples. Please see the attached screenshots.

Hope this helps!

![encoding_option](https://user-images.githubusercontent.com/615941/35256552-3b95b83e-ffa9-11e7-8021-2446676c721c.png)

![reconciliation](https://user-images.githubusercontent.com/615941/35256566-47c32862-ffa9-11e7-9a72-4f29d72637d6.png)

**Comment by mphilli** [comment]
The names appear normal prior to reconciliation, as you can see: 

![18237327119](https://user-images.githubusercontent.com/8686964/35281595-4250f97c-0021-11e8-8514-f812be436d89.PNG)

Also, the project is being created by using Excel data files (.xlsx), and when parsing data as Excel files, there doesn't seem to be any "Character encoding" option.

Note: I noticed that while the names appear normal in the original Excel files and in OpenRefine prior to reconciliation, any attempt to export the project (as .xlsx, .csv, etc...) will result in the names having encoding issues as well. (Perhaps it is related to [this issue](https://github.com/OpenRefine/OpenRefine/issues/929)?) Edit: But the instances where exporting the project screws up the encoding are not always the same as instances where there are encoding problems with reconciliation, so these things might be unrelated...

**Comment by codeforkjeff** [comment]
Could you attach an excel file with a few rows in it that are exhibiting this behavior? It would help me troubleshoot whether the problem lies with openrefine or conciliator.

**Comment by mphilli** [comment]
Actually, in my attempts at recreating the issue, the problem seems not be occurring. I don't know why, I didn't change anything: 

![f12392391](https://user-images.githubusercontent.com/8686964/35291870-b4d90f1e-003c-11e8-8c2d-820b63f20cc7.PNG)
![f129382181](https://user-images.githubusercontent.com/8686964/35291871-b4e2b9f6-003c-11e8-8e83-c77b83297629.PNG)

I will let you know if I am successful in recreating the issue, but it seems to be resolved for now... 

Edit: It seems strange that the reconciliation scores are ~.8, given that they seem like exact matches. Maybe it has to do with different encoding? Also, I don't know where the "." at the end of the reconciled result for Pidal Menéndez is coming from, but I'll leave that be...

**Comment by codeforkjeff** [comment]
Glad you got it working--please do check back in if you figure out what triggers the encoding issue.

The matches are not 100% exact; there is an additional comma and period in the authoritative names from LC.

**Comment by codeforkjeff** [comment]
re: the "." at the end, you're right, the actual LC name doesn't have a period at the end, but VIAF adds the period in the name that it reports to be from LC. This is in VIAF's searchRetrieveResponse/records/record/recordData/VIAFCluster/mainHeadings/data/text XML element.

I'll have to give some thought as to whether conciliator should remove it or not.

**Comment by codeforkjeff** [comment]
In the /src/test/resources directory, there are some XML files fetched from VIAF several months ago for a few test cases (Shakespeare, Steinbeck, some others). I don't see the period there for the LC names, so this is something VIAF changed at some point.

I'm reluctant to have conciliator change any of the data it gets. Maybe you could contact VIAF directly and point out that the names don't match exactly?

**Comment by mphilli** [comment]
I'm only using the conciliator program to fetch LCNAF IDs; I don't care much that they don't match exactly. It's just unfortunate, as it decreases the scores during reconciliation.
