### ISSUE TITLE
Add more information on configuring Solr datasources

### ISSUE THREAD

**Issue by alanorth** [codeforkjeff/conciliator#12]
I found it a bit tricky to set up a Solr datasource. I eventually succeeded, but only after grepping the source code for a few of the properties listed in `conciliator.properties` and doing lots of trial and error.

The comments in `conciliator.properties` could be expanded with a bit more information, for example: what each parameter does, what values they expect, if any are optional, how to add multiple sources (ie, for multiple fields), etc.

I've annotated `conciliator.properties` based on my limited knowledge of Solr and my testing of conciliator:

```
##  Name will appear in OpenRefine's reconciliation interface
# datasource.solr.name=A Solr Collection of Books

## Seems to be some internal type?
# datasource.solr.nametype.id=/book/book

## Seems to correspond to internal type somehow?
# datasource.solr.nametype.name=Book

## Solr query URL with placeholders for query term and rows (will be replaced by conciliator for each query)
# datasource.solr.url.query=http://localhost:8983/solr/test-core/select?wt=xml&q={{QUERY}}&rows={{ROWS}}

## Not sure why we need to get each matching document
# datasource.solr.url.document=http://localhost:8983/solr/test-core/get?id={{id}}

## ???
# datasource.solr.field.id=id

## Solr field name (sounds like Solr's filter list parameter, not sure why we need this if we could just search for the field directly in the query URL?)
# datasource.solr.field.name=title_display

## can be 'concat' or 'first'. defaults to 'concat'
# datasource.solr.field.name.multivalue.strategy=first
# datasource.solr.field.name.multivalue.delimiter=,
```

I'd appreciate your feedback. Thanks!

**Comment by codeforkjeff** [comment]
Thanks for taking the time to do this! I've added your comments to the file and also tweaked some of them. I'm sure it will help other users. Some notes:

datasource.solr.url.document is the URL that OpenRefine uses to hyperlink candidates for a match; conciliator does not actually load the URL.

datasource.solr.field.id is the ID field in the Solr document, that conciliator passes to OpenRefine as the ID of the match.

datasource.solr.field.name is the field in the Solr document that conciliator uses for the display name. It's not used for searching at all; as you note, that is handled by datasource.solr.url.query.

Let me know if you have any other questions!

**Comment by alanorth** [comment]
No problem. Thank you for making conciliator. I'm just getting started with it, but I can tell it's very well made and you put a lot of work into it. I'll get back to you if I have more questions.
