### ISSUE TITLE
Issue with Java 10

### ISSUE THREAD

**Issue by Aubreymcfato** [codeforkjeff/conciliator#16]
hello, I'd like to report an error with my Java:

```
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)
```
here's the complete log, I hope it's helpful.
[java1.txt](https://github.com/codeforkjeff/conciliator/files/2383772/java1.txt)

**Comment by codeforkjeff** [comment]
Thank you so much for reporting this!

I've committed a fix and made a new release, v3.0.3. Please give it a try. Hopefully there are no other issues with java 9 or 10 (I haven't had a chance to extensively test conciliator with these newer versions).

**Comment by Aubreymcfato** [comment]
It seems perfect. 
Thank you very much, I use conciliator all the time ;-)

**Comment by codeforkjeff** [comment]
Glad to hear it! I'll close this out, feel free to open another issue if you encounter other problems.
