### ISSUE TITLE
Service does not work as of around August 2022

### ISSUE THREAD

**Issue by timothy-mendenhall** [codeforkjeff/conciliator#26]
As of around August 2022, the reconciliation service will run but will not return any results, even for exact matches, at least for the http://refine.codefork.com/reconcile/viafproxy/LC option.  I have tried the service using different versions of OpenRefine (3.5.2, which historically worked fine with this service, and 3.6), but it does not seem to work.  I wonder if the VIAF APIs have been updated, necessitating changes to the reconciliation service?

**Comment by codeforkjeff** [comment]
Thanks for taking the time to report this! This should be fixed now. Please let me know if you're still having difficulties getting results for VIAF.

**Comment by timothy-mendenhall** [comment]
Thanks Jeff--it works now as before!

**Comment by timothy-mendenhall** [comment]
I seem to be experiencing this same issue again -- the service runs but does not actually reconcile anything

**Comment by codeforkjeff** [comment]
I'm seeing successful queries in the last day on the service running at https://refine.codefork.com/reconcile/viaf though there are some intermittent errors from VIAF, which is not unusual. If you're running the service on your own machine or servers, could you post any error messages you're seeing?

**Comment by timothy-mendenhall** [comment]
Sorry for the lag in response time--I was out on vacation for the past week.  I have never quite been able to get the service to run correctly on my Macbook (I am not so technically savvy with this type of application), so I do use the public service, specifically http://localhost:8080/reconcile/viafproxy/LC 
The service does seem to run, but even with exact string matches it returns no matches from VIAF.  
<img width="763" alt="Screen Shot 2022-09-13 at 10 50 16 AM" src="https://user-images.githubusercontent.com/2761571/189934995-947e8e06-7199-4cdf-889c-25579738ca2d.png">

**Comment by timothy-mendenhall** [comment]
Error in the previous comment -- I meant to say that I use the public service at https://refine.codefork.com/reconcile/viafproxy/LC

**Comment by timothy-mendenhall** [comment]
Sorry for so many comments -- I just deleted the existing service I was using in OpenRefine, and tried to set it up again with the URL from the documentation page (https://refine.codefork.com/)  https://refine.codefork.com/reconcile/viafproxy/LC , and OpenRefine gave me this error (screenshot attached) 
<img width="488" alt="Screen Shot 2022-09-13 at 11 03 02 AM" src="https://user-images.githubusercontent.com/2761571/189937456-5e31e309-e8a2-4ebb-836d-3df8e62b35a6.png">

**Comment by codeforkjeff** [comment]
@timothy-mendenhall I've been upgrading/modernizing some pieces of the application, and forgot to add CORS support for the viafproxy and source-specific viaf routes. It was falling back to JSONP and failing.

This should be fixed now, apologies. Please try https://refine.codefork.com/reconcile/viafproxy/LC again.

**Comment by timothy-mendenhall** [comment]
Thanks for updating!  The service works great now.
