### ISSUE TITLE
Available properties for ORCID?

### ISSUE THREAD

**Issue by wetneb** [codeforkjeff/conciliator#7]
Hi!
Thanks for your ORCID reconciliation service. I wonder if it supports any property? It would be great if we could use Researcher ID, Scopus ID, ISNI, institutions, or other things like that. We're using it at WikiCite 2017 to add ORCID ids to Wikidata items for researchers.

**Comment by codeforkjeff** [comment]
Hi, it doesn't support any properties yet, but I will look into implementing this. I've been super busy with work lately, sorry! It may take a little while before I get to this.

**Comment by codeforkjeff** [comment]
I cut a new release, v2.4.0, that supports properties as fielded searches. See the updated README for links to ORCID documentation pages for the valid field names to use. Let me know how this works for you.

**Comment by wetneb** [comment]
@codeforkjeff that is awesome, thank you so much! I'll liase with the other users.
